language: ruby
script: bundle exec rake
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  # - ruby-head
  # - ree
  # - rbx-18mode
  # - rbx-19mode
  # - jruby-18mode
  # - jruby-19mode
  # - jruby-head
